### ISSUE TITLE
Picard Tools 1.105 Location

### ISSUE THREAD

**Issue by FrostFlow13** [darrenabbey/ymap#13]
Hello! I wasn't entirely sure where to send this, so I decided "Issues" might be the most likely to be seen.

I did manage to find a link to Picard Tools 1.105 FROM the Broad Institute! Turns out, if you just change the URL, it'll let you bypass the weird page limit and go straight to it.

https://github.com/broadinstitute/picard/releases/tag/1.105

I hope that this helps! I'm currently trying to make a local version of Ymap on my lab's server, and I've had mixed success so far (admittedly this is also my first time ever trying to do something like this), but I figured if I can at least provide something to help people in the future I might as well!

EDIT: So, I tried to make 1.105 work for a while, but I personally wasn't able to get it functional. I did find that 1.120 seems to work fine, though, at least for everything I've been able to get running so far.

**Comment by darrenabbey** [comment]
Glad to know. I'll update my recommendations.
